name: Dart

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
           channel: 'stable'
           cache: true
      - run: flutter --version
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      
      - uses: actions/upload-artifact@v1
        with:
          name: onenote_code_formatter_helper_windows
          path: build/windows/runner/Release

      - uses: actions/download-artifact@v3
        with:
          name: onenote_code_formatter_helper_windows
